version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(module)s:%(lineno)d >> %(message)s"
  access:
    format: "%(asctime)s %(levelname)s >> %(message)s"


handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  file_access:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: access
    filename: "{LOG_DIR}/tutor-access.log"
    when: "midnight"
    interval: 1
    backupCount: 30
    encoding: utf-8
    delay: true

  file_error:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: standard
    filename: "{LOG_DIR}/tutor-app-error.log"
    when: "midnight"
    interval: 1
    backupCount: 30
    encoding: utf-8
    delay: true

  file_system:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: standard
    filename: "{LOG_DIR}/tutor-system.log"
    when: "midnight"
    interval: 1
    backupCount: 30
    encoding: utf-8
    delay: true

  file_app_stdout:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: "{LOG_DIR}/tutor-app-stdout.log"
    when: "midnight"
    interval: 1
    backupCount: 30
    encoding: utf-8
    delay: true

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [console, file_error]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [console, file_access]
    propagate: False

  # 사용자 직접 찍는 로그 전용
  app.stdout:
    level: DEBUG
    handlers: [console, file_app_stdout]
    propagate: False

  # 시스템성 로그(DB I/O, 배치 등)
  app.system:
    level: INFO
    handlers: [console, file_system]
    propagate: False

root:
  level: INFO
  handlers: [console, file_system, file_error]
